/**
 * TASK 16.4 — Entry Decision Trace Export. Architecture: FROZEN.
 *
 * Frozen input contracts for the Entry Decision trace. The caller feeds the
 * Entry Engine's recorded decision journey in; the exporter copies values
 * verbatim. READ ONLY: no check is re-evaluated, no score is recomputed,
 * the Entry Engine and RuleBook are never touched.
 */

import type { AiExportScalar } from '../types';

export type EntryTraceStatus = 'PASS' | 'FAIL' | 'WARNING' | 'SKIPPED';

export type EntryTraceBlockerType = 'HARD' | 'SOFT' | 'UNLOCK' | 'GROUP';

export type EntryTraceDecisionValue = 'ENTER' | 'WAIT' | 'AVOID';

export interface EntryTraceEvidence {
  label?: AiExportScalar;
  value?: AiExportScalar;
}

export interface EntryTraceMetadata {
  version?: AiExportScalar;
  tradeId?: AiExportScalar;
  coin?: AiExportScalar;
  side?: AiExportScalar;
  timestamp?: AiExportScalar;
  ruleVersion?: AiExportScalar;
  entryVersion?: AiExportScalar;
  scoreVersion?: AiExportScalar;
  engineVersion?: AiExportScalar;
}

/** One entry check — one evidence set, never duplicated (Explainability). */
export interface EntryTraceCheck {
  id?: AiExportScalar;
  name?: AiExportScalar;
  /** Rule identity copied from the engine. Never generated by the exporter. */
  ruleId?: AiExportScalar;
  ruleName?: AiExportScalar;
  status?: EntryTraceStatus | null;
  weight?: AiExportScalar;
  priority?: AiExportScalar;
  reason?: AiExportScalar;
  recommendation?: AiExportScalar;
  evidence?: readonly EntryTraceEvidence[] | null;
  actual?: AiExportScalar;
  expected?: AiExportScalar;
  threshold?: AiExportScalar;
  difference?: AiExportScalar;
  unit?: AiExportScalar;
  source?: AiExportScalar;
  /** Copied verbatim from the engine (e.g. "PASS", "+10", "-15"). */
  contribution?: AiExportScalar;
  dependency?: AiExportScalar;
  enabled?: boolean | null;
}

export interface EntryTraceBlocker {
  type?: EntryTraceBlockerType | null;
  trigger?: AiExportScalar;
  override?: boolean | null;
  rule?: AiExportScalar;
  reason?: AiExportScalar;
  priority?: AiExportScalar;
  evidence?: readonly EntryTraceEvidence[] | null;
}

export interface EntryTraceDecision {
  decision?: EntryTraceDecisionValue | null;
  initialDecision?: EntryTraceDecisionValue | null;
  override?: AiExportScalar;
  finalDecision?: EntryTraceDecisionValue | null;
  reason?: AiExportScalar;
  summary?: AiExportScalar;
  confidence?: AiExportScalar;
  grade?: AiExportScalar;
  recommendation?: AiExportScalar;
}

/** One stage of the Entry Engine decision tree, copied in engine order. */
export interface EntryTraceTreeStep {
  stage?: AiExportScalar;
  result?: AiExportScalar;
  detail?: AiExportScalar;
}

/** RuleBook state transition observed by the Entry Engine (READY/WATCH/LOCKED/BLOCKED). */
export interface EntryTraceRuleBookInteraction {
  stateBefore?: AiExportScalar;
  stateAfter?: AiExportScalar;
  triggerRule?: AiExportScalar;
  reason?: AiExportScalar;
}

/** Frozen summary counters/state supplied by the Entry Engine. Never counted here. */
export interface EntryTraceSummary {
  passedChecks?: AiExportScalar;
  warnings?: AiExportScalar;
  failedChecks?: AiExportScalar;
  hardBlocks?: AiExportScalar;
  groupBlocks?: AiExportScalar;
  softBlocks?: AiExportScalar;
  unlockRules?: AiExportScalar;
  decision?: AiExportScalar;
  confidence?: AiExportScalar;
  grade?: AiExportScalar;
  ruleBookState?: AiExportScalar;
}

/** Full frozen input for one Entry Decision Trace export run. */
export interface EntryTraceInput {
  metadata?: EntryTraceMetadata | null;
  /** Frozen market snapshot the Entry Engine received (EMA, Volume, Funding, ...). */
  inputSnapshot?: Readonly<Record<string, AiExportScalar>> | null;
  decision?: EntryTraceDecision | null;
  decisionTree?: readonly EntryTraceTreeStep[] | null;
  checks?: readonly EntryTraceCheck[] | null;
  blockers?: readonly EntryTraceBlocker[] | null;
  ruleBook?: EntryTraceRuleBookInteraction | null;
  entrySummary?: EntryTraceSummary | null;
}

export interface EntryTraceEvidenceItem {
  label: string;
  value: string;
}

export interface EntryTraceCheckItem {
  index: number;
  id: string;
  name: string;
  ruleId: string;
  ruleName: string;
  status: string;
  weight: string;
  priority: string;
  reason: string;
  recommendation: string;
  evidence: readonly EntryTraceEvidenceItem[];
  actual: string;
  expected: string;
  threshold: string;
  difference: string;
  unit: string;
  source: string;
  contribution: string;
  dependency: string;
  ignored: boolean;
}

export interface EntryTraceBlockerItem {
  index: number;
  type: string;
  trigger: string;
  override: boolean | null;
  rule: string;
  reason: string;
  priority: string;
  evidence: readonly EntryTraceEvidenceItem[];
}

export interface EntryTraceTreeStepItem {
  index: number;
  stage: string;
  result: string;
  detail: string;
}

export interface EntryTraceConflict {
  detected: boolean;
  reasons: readonly string[];
}

/** Builder output — normalized, no undefined, ready for formatting. */
export interface EntryTrace {
  metadata: EntryTraceMetadata;
  inputSnapshot: readonly { key: string; value: string }[];
  decision: EntryTraceDecision;
  decisionTree: readonly EntryTraceTreeStepItem[];
  checks: readonly EntryTraceCheckItem[];
  blockers: readonly EntryTraceBlockerItem[];
  ruleBook: EntryTraceRuleBookInteraction;
  entrySummary: EntryTraceSummary;
  conflict: EntryTraceConflict;
}
