/**
 * AI REVIEW SPECIFICATION v1 — static documentation embedded in every
 * Phase 16 Trace and Phase 17 Review export.
 *
 * REVIEW PROTOCOL LOCK (FINAL): this section IS the official, locked review
 * contract (see docs/REVIEW_PROTOCOL.md). Documentation only: no runtime
 * values, calculations, or inferred data.
 */

const DIVIDER = '--------------------------------';

/** Return the deterministic Markdown section shared by all export formatters. */
export function aiReviewSpecificationSection(): readonly string[] {
  return [
    DIVIDER,
    '',
    '# AI REVIEW SPECIFICATION',
    '',
    'Review Protocol: v1 (LOCKED). See REVIEW_PROTOCOL.md.',
    '',
    'This exported document is self-contained.',
    '',
    'Reviewer AI MUST follow these rules. No external prompt is required.',
    '',
    DIVIDER,
    '',
    '## SOURCE OF TRUTH',
    '',
    'The exported snapshot is the ONLY source of truth.',
    '',
    'Do NOT infer hidden engine behavior.',
    '',
    'Do NOT reconstruct internal calculations.',
    '',
    'Evaluate ONLY exported values.',
    '',
    DIVIDER,
    '',
    '## EXPORT SCOPE',
    '',
    'This document contains:',
    '',
    '- Runtime snapshot values',
    '- Rule relationships',
    '- Decision results',
    '- Structural evidence',
    '- Documented formulas',
    '',
    'This document intentionally may omit:',
    '',
    '- Internal cache',
    '- Temporary variables',
    '- Engine private state',
    '- Intermediate calculations',
    '',
    'Missing exported fields MUST NOT be treated as implementation defects.',
    '',
    DIVIDER,
    '',
    '## REVIEW RULES',
    '',
    'Rule 1: Evaluate ONLY exported values.',
    '',
    'Rule 2: Never infer hidden calculations.',
    '',
    'Rule 3: If exported evidence is insufficient, classify as INSUFFICIENT EVIDENCE.',
    '',
    'Rule 4: Missing diagnostic fields are ENHANCEMENT, NOT BUG.',
    '',
    'Rule 5: A BUG requires exported evidence proving that the implementation violates the RuleBook.',
    '',
    'Rule 6: Do NOT report a bug using assumptions.',
    '',
    'Rule 7: Block Type MUST be derived only via BLOCK TYPE RESOLUTION table '
      + 'above (Hard list / Score list membership). Any Block Type not traceable '
      + 'to list membership is a candidate BUG, regardless of Mandatory or Status.',
    '',
    'Reviewer AI MUST:',
    '',
    '- Evaluate only exported values.',
    '- Treat the exported snapshot as the only source of truth.',
    '- Respect documented formulas.',
    '- Respect documented transformations.',
    '- Respect the documented Gate hierarchy.',
    '',
    'Reviewer AI MUST NOT:',
    '',
    '- Infer hidden calculations.',
    '- Reconstruct engine internals.',
    '- Guess missing snapshot values.',
    '- Assume undocumented Rule behavior.',
    '- Report bugs using assumptions.',
    '',
    DIVIDER,
    '',
    '## SCORING INTERPRETATION',
    '',
    'Displayed Scores are normalized values.',
    '',
    'Display Layer Score (Score Trace / Rule Trace): per-layer display scale (max 1.5 each).',
    'Do NOT hand-sum Display Layer Scores and compare to Decision Total — they use different scales.',
    '',
    'Decision Total (snap.score): Group-scale total (max 15). Copied from the frozen snapshot.',
    'This is the authoritative score for decision bands.',
    '',
    'GROUP BREAKDOWN: Group A + Group B + Group C = Decision Total.',
    'Group Scores are copied from engine groupScores — not reverse-fitted from the total.',
    '',
    'Hand-sum of Display Layer Scores ≠ Decision Total is expected (two scales) — NOT a bug',
    'unless GROUP BREAKDOWN contradicts Decision Total.',
    '',
    'Bonus values are applied to Internal Raw Scores.',
    '',
    'Displayed Scores MUST NOT be compared directly against Raw Bonus values.',
    '',
    'Reviewer AI must evaluate the documented transformation before reporting inconsistencies.',
    '',
    DIVIDER,
    '',
    '## BLOCK INTERPRETATION',
    '',
    'Hard Blocks may originate from:',
    '',
    '- RuleBook',
    '- Independent Gates',
    '- Pre-Filters',
    '',
    'Hard Blocks are NOT Score penalties.',
    '',
    'Gate ≠ RuleBook Rule.',
    '',
    DIVIDER,
    '',
    '## BLOCK TYPE RESOLUTION (DETERMINISTIC — DO NOT INFER)',
    '',
    'Block Type of a rule/layer is determined ONLY by list membership below.',
    'It is NEVER inferred from Status, Mandatory, or Actual vs Expected.',
    '',
    '| Rule/Layer name appears in... | Block Type |',
    '|---|---|',
    '| "Hard Blocks (Engine / All Sources)" list in BLOCKING EVENTS ORIGIN | HARD |',
    '| "Score Blocks (block reasons)" list in BLOCKING EVENTS ORIGIN, AND not in Hard list above | SOFT |',
    '| Neither list | NONE |',
    '',
    'FORBIDDEN INFERENCE (explicitly disallowed — this caused a real bug, fixed 2026-07-22):',
    '- Mandatory = YES does NOT imply Block Type = HARD.',
    '- Status = FAIL does NOT imply Block Type = HARD.',
    '- Actual < Expected does NOT imply Block Type = HARD.',
    'Mandatory, Status, and Block Type are THREE INDEPENDENT fields. A rule can be',
    'Mandatory=YES + Status=FAIL + Block Type=SOFT simultaneously — this is valid',
    'and expected, not a contradiction.',
    '',
    '## Worked examples (canonical reference — use these to self-check before reporting a bug)',
    '',
    '| Trade | Rule | Status | Mandatory | Actual vs Expected | In Hard list? | In Score list? | Correct Block Type |',
    '|---|---|---|---|---|---|---|---|',
    '| BTCUSDT-SHORT | L5a | FAIL | YES | 0 < 1.5 | NO | YES | SOFT |',
    '| SOLUSDT-SHORT | L5a | PASS | YES | 0.38 < 1.5 | NO | YES | SOFT |',
    '| NEARUSDT-SHORT | L5a | PASS | YES | 1.5 = 1.5 | NO | NO | NONE |',
    '| (hypothetical) any-SHORT | L5a | FAIL | YES | CVD extreme | YES | — | HARD |',
    '| NEARUSDT-SHORT | L3 | PASS | NO | L3 raw 1.0 (≥1 shared, <1.5 NEAR gate) | YES (NEAR SHORT — L3 MACD < 1.5…) | NO | HARD |',
    '',
    'NEAR-only S1 note: hard reason string starts with "NEAR SHORT — L3 MACD…"',
    '(not "^L3"). Rule Trace still maps it to L3 Block Type=HARD via list membership',
    '+ layer matcher. S1 does NOT flip L3 passed→false; Warning Count stays soft-fail-only',
    '(same pattern as other hard gates — not the old warningLayerCountFromSnap bug class).',
    '',
    'Reviewer AI MUST cross-check the two lists in BLOCKING EVENTS ORIGIN before',
    'assigning any Block Type verdict. If a rule\'s Block Type in the export does',
    'NOT match this table\'s derivation from the two lists, classify as BUG with',
    'exact list membership as evidence — not as INSUFFICIENT EVIDENCE or ENHANCEMENT.',
    '',
    DIVIDER,
    '',
    '## SNAPSHOT CAPABILITY',
    '',
    'This export represents the frozen runtime snapshot.',
    '',
    'If a value is marked UNAVAILABLE, it means:',
    '',
    '"Not stored in this snapshot version."',
    '',
    'It does NOT imply:',
    '',
    '- Calculation failure',
    '- Engine defect',
    '- Export bug',
    '',
    'Reviewer AI MUST classify missing snapshot capability as ENHANCEMENT unless exported evidence proves otherwise.',
    '',
    DIVIDER,
    '',
    '## REVIEW CLASSIFICATION',
    '',
    'Every finding MUST belong to exactly one category:',
    '',
    '- PASS — Implementation is consistent with exported evidence.',
    '- BUG — Exported evidence proves a RuleBook violation. A BUG must always '
      + 'reference exported evidence. No assumptions allowed.',
    '- INSUFFICIENT EVIDENCE — The exported snapshot does not contain enough '
      + 'information to verify the finding. Reviewer must stop speculation.',
    '- ENHANCEMENT — The implementation is correct; additional exported '
      + 'information could improve future review quality. Enhancement is NOT a bug.',
    '',
    'No other verdict is allowed.',
    '',
    DIVIDER,
    '',
    '## REVIEW ORDER',
    '',
    '1. Verify snapshot completeness.',
    '2. Verify Rule consistency.',
    '3. Verify structural consistency.',
    '4. Verify Decision consistency.',
    '5. Verify exported Evidence.',
    '6. Suggest Enhancements.',
    '',
    'Reviewer MUST NOT skip steps.',
  ];
}
