/**
 * AI REVIEW SPECIFICATION v1 — static documentation embedded in every
 * Phase 16 Trace and Phase 17 Review export.
 *
 * REVIEW PROTOCOL LOCK (FINAL): this section IS the official, locked review
 * contract (see docs/REVIEW_PROTOCOL.md). Documentation only: no runtime
 * values, calculations, or inferred data.
 */

const DIVIDER = '--------------------------------';

/** Return the deterministic Markdown section shared by all export formatters. */
export function aiReviewSpecificationSection(): readonly string[] {
  return [
    DIVIDER,
    '',
    '# AI REVIEW SPECIFICATION',
    '',
    'Review Protocol: v1 (LOCKED). See REVIEW_PROTOCOL.md.',
    '',
    'This exported document is self-contained.',
    '',
    'Reviewer AI MUST follow these rules. No external prompt is required.',
    '',
    DIVIDER,
    '',
    '## SOURCE OF TRUTH',
    '',
    'The exported snapshot is the ONLY source of truth.',
    '',
    'Do NOT infer hidden engine behavior.',
    '',
    'Do NOT reconstruct internal calculations.',
    '',
    'Evaluate ONLY exported values.',
    '',
    DIVIDER,
    '',
    '## EXPORT SCOPE',
    '',
    'This document contains:',
    '',
    '- Runtime snapshot values',
    '- Rule relationships',
    '- Decision results',
    '- Structural evidence',
    '- Documented formulas',
    '',
    'This document intentionally may omit:',
    '',
    '- Internal cache',
    '- Temporary variables',
    '- Engine private state',
    '- Intermediate calculations',
    '',
    'Missing exported fields MUST NOT be treated as implementation defects.',
    '',
    DIVIDER,
    '',
    '## REVIEW RULES',
    '',
    'Rule 1: Evaluate ONLY exported values.',
    '',
    'Rule 2: Never infer hidden calculations.',
    '',
    'Rule 3: If exported evidence is insufficient, classify as INSUFFICIENT EVIDENCE.',
    '',
    'Rule 4: Missing diagnostic fields are ENHANCEMENT, NOT BUG.',
    '',
    'Rule 5: A BUG requires exported evidence proving that the implementation violates the RuleBook.',
    '',
    'Rule 6: Do NOT report a bug using assumptions.',
    '',
    'Reviewer AI MUST:',
    '',
    '- Evaluate only exported values.',
    '- Treat the exported snapshot as the only source of truth.',
    '- Respect documented formulas.',
    '- Respect documented transformations.',
    '- Respect the documented Gate hierarchy.',
    '',
    'Reviewer AI MUST NOT:',
    '',
    '- Infer hidden calculations.',
    '- Reconstruct engine internals.',
    '- Guess missing snapshot values.',
    '- Assume undocumented Rule behavior.',
    '- Report bugs using assumptions.',
    '',
    DIVIDER,
    '',
    '## SCORING INTERPRETATION',
    '',
    'Displayed Scores are normalized values.',
    '',
    'Display Layer Score (Score Trace / Rule Trace): per-layer display scale (max 1.5 each).',
    'Do NOT hand-sum Display Layer Scores and compare to Decision Total — they use different scales.',
    '',
    'Decision Total (snap.score): Group-scale total (max 15). Copied from the frozen snapshot.',
    'This is the authoritative score for decision bands.',
    '',
    'GROUP BREAKDOWN: Group A + Group B + Group C = Decision Total.',
    'Group Scores are copied from engine groupScores — not reverse-fitted from the total.',
    '',
    'Hand-sum of Display Layer Scores ≠ Decision Total is expected (two scales) — NOT a bug',
    'unless GROUP BREAKDOWN contradicts Decision Total.',
    '',
    'Bonus values are applied to Internal Raw Scores.',
    '',
    'Displayed Scores MUST NOT be compared directly against Raw Bonus values.',
    '',
    'Reviewer AI must evaluate the documented transformation before reporting inconsistencies.',
    '',
    DIVIDER,
    '',
    '## BLOCK INTERPRETATION',
    '',
    'Hard Blocks may originate from:',
    '',
    '- RuleBook',
    '- Independent Gates',
    '- Pre-Filters',
    '',
    'Hard Blocks are NOT Score penalties.',
    '',
    'Gate ≠ RuleBook Rule.',
    '',
    DIVIDER,
    '',
    '## SNAPSHOT CAPABILITY',
    '',
    'This export represents the frozen runtime snapshot.',
    '',
    'If a value is marked UNAVAILABLE, it means:',
    '',
    '"Not stored in this snapshot version."',
    '',
    'It does NOT imply:',
    '',
    '- Calculation failure',
    '- Engine defect',
    '- Export bug',
    '',
    'Reviewer AI MUST classify missing snapshot capability as ENHANCEMENT unless exported evidence proves otherwise.',
    '',
    DIVIDER,
    '',
    '## REVIEW CLASSIFICATION',
    '',
    'Every finding MUST belong to exactly one category:',
    '',
    '- PASS — Implementation is consistent with exported evidence.',
    '- BUG — Exported evidence proves a RuleBook violation. A BUG must always '
      + 'reference exported evidence. No assumptions allowed.',
    '- INSUFFICIENT EVIDENCE — The exported snapshot does not contain enough '
      + 'information to verify the finding. Reviewer must stop speculation.',
    '- ENHANCEMENT — The implementation is correct; additional exported '
      + 'information could improve future review quality. Enhancement is NOT a bug.',
    '',
    'No other verdict is allowed.',
    '',
    DIVIDER,
    '',
    '## REVIEW ORDER',
    '',
    '1. Verify snapshot completeness.',
    '2. Verify Rule consistency.',
    '3. Verify structural consistency.',
    '4. Verify Decision consistency.',
    '5. Verify exported Evidence.',
    '6. Suggest Enhancements.',
    '',
    'Reviewer MUST NOT skip steps.',
  ];
}
