/**
 * Shared Asia/Ho_Chi_Minh build-date helpers for BUILD_INFO + in-app stamp.
 * Used by scripts/stamp-build-date.mjs and scripts/write-build-info.mjs.
 */
import fs from 'fs';
import path from 'path';

export const BUILD_TZ = 'Asia/Ho_Chi_Minh';

/** YYYY-MM-DD in Asia/Ho_Chi_Minh */
export function getBuildDateYmd(now = new Date()) {
  return new Intl.DateTimeFormat('en-CA', {
    timeZone: BUILD_TZ,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(now);
}

/** `YYYY-MM-DD HH:mm:ss` in Asia/Ho_Chi_Minh (same clock as getBuildDateYmd) */
export function getBuildTimestampLocal(now = new Date()) {
  const parts = new Intl.DateTimeFormat('en-GB', {
    timeZone: BUILD_TZ,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  }).formatToParts(now);
  const g = (type) => parts.find((p) => p.type === type)?.value ?? '00';
  return `${g('year')}-${g('month')}-${g('day')} ${g('hour')}:${g('minute')}:${g('second')}`;
}

export function buildDateGeneratedPath(root) {
  return path.join(root, 'constants', 'buildDate.generated.ts');
}

/** Writes constants/buildDate.generated.ts - source consumed by constants/buildInfo.ts */
export function writeBuildDateGenerated(root, ymd = getBuildDateYmd()) {
  const out = buildDateGeneratedPath(root);
  const body = `/** AUTO-GENERATED by stamp-build-date / write-build-info - do not edit by hand. */
export const BUILD_DATE_YMD = '${ymd}' as const;
`;
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, body, 'utf8');
  return { path: out, buildDate: ymd };
}
