/**
 * Task 15.3 — Insight rule thresholds (deterministic constants).
 */

export const INSIGHT_RULES = {
  MIN_TRADES_FOR_COMPARE: 3,
  MIN_TRADES_FOR_COIN: 2,
  MIN_TRADES_FOR_TIMING: 3,
  MIN_HOUR_TRADES: 2,
  RR_TARGET: 1.5,
  HOLD_LONG_MINUTES: 240,
  LATE_HOUR_START: 22,
  WIN_RATE_STRONG: 55,
  WIN_RATE_WEAK: 40,
  PF_STRONG: 1.5,
  PF_WEAK: 1.0,
  CONSISTENCY_WEAK: 40,
  CONSISTENCY_STRONG: 60,
  RISK_HIGH_SCORE: 55,
  RISK_CRITICAL_SCORE: 75,
  EXPECTANCY_FALL_ABS: 0.5,
  WR_IMPROVE_ABS: 3,
  DD_IMPROVE_ABS: 0.01,
  LOSING_STREAK_WARN: 3,
  LOSING_STREAK_CRIT: 5,
} as const;
